version: "3.9"
services:

  visualizer:
    image: bretfisher/visualizer
    ports:
      - 8008:8080
    stop_grace_period: 1m30s
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      placement:
        constraints: [node.role == manager]
